version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      WEATHER_API_KEY: ${WEATHER_API_KEY}
      WEATHER_API_BASE_URL: ${WEATHER_API_BASE_URL}
      WEATHER_APP_ENV: ${WEATHER_APP_ENV}
      WEATHER_MAX_RETRIES: ${WEATHER_MAX_RETRIES}
      WEATHER_REDIS_URL: redis://redis:6379
      WEATHER_TIME_PERIOD: ${WEATHER_TIME_PERIOD}
    depends_on:
      - redis

  redis:
    image: "redis:6.2"
    ports:
      - "6379:6379"